version: '3'

services:
  certbot:
    image: certbot/certbot:latest
    command: sh -c "certbot renew"
    entrypoint: ""
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
