version: '3'

services:
  yaqluator_app:
    container_name: yaqluator_app
    restart: always
    build: ./
    volumes:
      - ./python:/var/www/yaqluator.com
    ports:
      - "8000:8000"
    command: gunicorn --workers 1 --bind 0.0.0.0:8000 --log-file=yaqluator_app.log wsgi:application
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - ./public_html:/usr/share/nginx/html:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "${YAQLUATOR_HTTP_PORT:-80}:80"
      - "${YAQLUATOR_HTTPS_PORT:-443}:443"
    depends_on:
      - yaqluator_app
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
